site_name: starlightDocs
theme: readthedocs
site_url: http://starlight-manual.readthedocs.io/
google_analytics: ['UA-86947939-2', 'mkdocs.org']
pages:
  - About: index.md
  - Features: features.md
  - Getting Started:
    - Installation: installation.md
    - User Interface: interface.md
    - Fog: fog.md
  - Support:
    - Release Notes: release-notes.md
    - Frequently Asked Questions: faq.md
    - Known Issues: issues.md
    - Contact: contact.md

